{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeportal.secretName" . }}
  labels:
    {{- include "kubeportal.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "postgresql.auth.password est obligatoire" .Values.postgresql.auth.password | quote }}
  INITIAL_ADMIN_PASSWORD: {{ required "initialAdmin.password est obligatoire" .Values.initialAdmin.password | quote }}
{{- end }}
